repos:
-   repo: git@github.com:psf/black.git
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: git@github.com:PyCQA/flake8.git
    rev: 3.9.2
    hooks:
    - id: flake8