repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: pdoc  
      name: pdoc
      description: 'pdoc3: Auto-generate API documentation for Python projects'
      entry: pdoc --html --skip-errors --force -o docs/api carvekit
      language: python
      language_version: python3
      require_serial: true
      types: [python]
